name: grocries_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.2
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  color: "#53B175"

  image: image/splash4.png
  android_12:
    color: "#53B175"
    image: image/splash4.png

flutter:
  uses-material-design: true

  assets:
    - image/
    - image/onbording (1).png